name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - staging
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      artifact-path: ${{ steps.export-artifact-path.outputs.path }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.20'
          cache: 'npm'

      - name: Install Dependencies
        run: yarn install --prefer-offline

      - name: Build Project
        run: |
          if [[ "${{ github.ref_name }}" == "dev" ]]; then
            CI=false yarn build:dev
          elif [[ "${{ github.ref_name }}" == "staging" ]]; then
            CI=false yarn build:staging
          elif [[ "${{ github.ref_name }}" == "main" ]]; then
            CI=false yarn build:production
          fi

      - name: Export Artifact Path
        id: export-artifact-path
        run: echo "path=build" >> $GITHUB_OUTPUT

      - name: Upload Build Output
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    # Dynamic Environment Selection
    environment:
      name: ${{ github.ref_name == 'main' && 'production' || github.ref_name }}

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: app-build
          path: build

      - name: Deploy to S3
        run: aws s3 sync build/ s3://$AWS_S3_BUCKET --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
          AWS_S3_BUCKET: ${{ vars.AWS_S3_BUCKET }}

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
          DISTRIBUTION_ID: ${{ vars.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
